spring.application.name=product-service
server.port=8083

spring.data.mongodb.uri=mongodb+srv://admin_user:catherinodatabase12345@cluster0.sfjx6rt.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=Database_Catherino
